### ISSUE TITLE
fails with Qt 5.10

### ISSUE THREAD

**Issue by jkarneges** [psi-plus/qconf#15]
The version check in `qmake_check` uses `?.?.?`, expecting a single digit for each version part.

**Comment by Ri0n** [comment]
and in a couple of minutes we see this bug closed by a commit ? ;-)

**Comment by jkarneges** [comment]
hopefully :)

**Comment by jkarneges** [comment]
Fix was simple, but getting Qt 5.10 to test against took more than a few minutes ;) (issue was reported by one of our users)

I didn't test with Windows, but the configwin code looks like it didn't have this problem.
